/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Prototype(props) {
  const { nodes, materials } = useGLTF('/prototype.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.057, 0]}>
        <group position={[0, 0.782, 1.024]} rotation={[-1.089, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['ECRAN_HMI_VRAI-1_-_Part'].geometry}
            material={materials['color-3.050']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['ECRAN_HMI_VRAI-1_-_Part_2'].geometry}
            material={materials['482300778_491872853977799_8533583894115208954_n']}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['c-2416049-7-a1-3digs-1_-_Part'].geometry}
          material={materials['color-3.048']}
          position={[0, 0.77, 1.129]}
          rotation={[-1.089, 0, 1.541]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['HMI_CASING_02-1_-_Part'].geometry}
          material={materials['color-3.049']}
          position={[0, 0.787, 1.027]}
          rotation={[0.482, 0, 0]}
        />
        <group position={[-0.362, -0.023, 1.042]} rotation={[-1.082, -Math.PI / 2, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Boss-Extru3_-_Part'].geometry}
            material={materials['color-3.022']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Congé1_3_-_Part'].geometry}
            material={materials['color-3.021']}
          />
        </group>
        <group position={[0.362, -0.023, 1.042]} rotation={[-1.082, -Math.PI / 2, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Boss-Extru3_-_Part_2'].geometry}
            material={materials['color-3.025']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Congé1_4_-_Part'].geometry}
            material={materials['color-3.024']}
          />
        </group>
        <group position={[-0.362, 0.064, 0.94]} rotation={[0, 1.571, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Boss-Extru12_-_Part'].geometry}
            material={materials['White-PW-MT11050-3.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Congé22_-_Part'].geometry}
            material={materials['White-PW-MT11050-3.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Congé23_-_Part'].geometry}
            material={materials['White-PW-MT11050-3.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Enlèv_mat-Extru16_-_Part_2'].geometry}
            material={materials['White-PW-MT11050-4']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Enlèv_mat-Extru16_-_Part'].geometry}
            material={materials['White-PW-MT11050-3']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Enlèv_mat-Extru17_-_Part_2'].geometry}
            material={materials['White-PW-MT11050-4.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Enlèv_mat-Extru17_-_Part'].geometry}
            material={materials['White-PW-MT11050-3.001']}
          />
        </group>
        <group position={[0.362, 0.064, 0.94]} rotation={[0, 1.571, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Boss-Extru12_-_Part_2'].geometry}
            material={materials['White-PW-MT11050-3.009']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Congé22_2_-_Part'].geometry}
            material={materials['White-PW-MT11050-3.008']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Congé23_2_-_Part'].geometry}
            material={materials['White-PW-MT11050-3.007']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Enlèv_mat-Extru16_-_Part_3'].geometry}
            material={materials['White-PW-MT11050-3.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Enlèv_mat-Extru16_-_Part_4'].geometry}
            material={materials['White-PW-MT11050-4.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Enlèv_mat-Extru17_-_Part_3'].geometry}
            material={materials['White-PW-MT11050-3.006']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Enlèv_mat-Extru17_-_Part_4'].geometry}
            material={materials['White-PW-MT11050-4.003']}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['91290A336_Alloy_Steel_Socket_Head_Screw-2_3_-_Part'].geometry}
          material={materials['color.013']}
          position={[0.354, 0, 0.93]}
          rotation={[-1.758, -1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-01-046-2_-_Part'].geometry}
          material={materials['White-PW-MT11050-7.001']}
          position={[0.303, 0, 0.417]}
          rotation={[Math.PI, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-01-075-2_-_Part'].geometry}
          material={materials['White-PW-MT11050-6.001']}
          position={[-0.259, 0, 0.417]}
          rotation={[-2.239, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-01-076-2_-_Part'].geometry}
          material={materials['Satin Finish Titanium.001']}
          position={[-0.362, 0.399, 1.003]}
          rotation={[0, 1.345, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-01-077-2_-_Part'].geometry}
          material={materials['White-PW-MT11050-5.002']}
          position={[-0.339, 0.383, 0.902]}
          rotation={[-2.214, 0.137, 2.961]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-01-077-4_-_Part'].geometry}
          material={materials['White-PW-MT11050-5.003']}
          position={[-0.247, 0.069, 0.504]}
          rotation={[-0.668, 1.392, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-01-080-2_-_Part'].geometry}
          material={materials['color-3.026']}
          position={[-0.347, -0.053, 0.015]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['tige_15_625mm-2_-_Part'].geometry}
          material={materials['polished steel.006']}
          position={[0.237, 0.035, 0.462]}
          rotation={[-1.361, -1.34, -2.25]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-01-019-1_-_Part'].geometry}
          material={materials['color.007']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-01-022-1_-_Part'].geometry}
          material={materials['color.008']}
          position={[-0.362, 0, 0.495]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-01-022-2_-_Part'].geometry}
          material={materials['color.011']}
          position={[0.362, 0, 0.495]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-01-024-2_-_Part'].geometry}
          material={materials['color.012']}
          position={[0.362, 0.254, 1.003]}
          rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-01-029-1_-_Part'].geometry}
          material={materials['polished steel.004']}
          position={[0, 0, 0.417]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-01-046-1_-_Part'].geometry}
          material={materials['White-PW-MT11050-7']}
          position={[-0.303, 0, 0.417]}
          rotation={[Math.PI, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-01-075-1_-_Part'].geometry}
          material={materials['White-PW-MT11050-6']}
          position={[0.209, 0, 0.417]}
          rotation={[-2.239, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-01-076-1_-_Part'].geometry}
          material={materials['Satin Finish Titanium']}
          position={[0.362, 0.399, 1.003]}
          rotation={[-Math.PI, 1.345, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-01-077-1_-_Part'].geometry}
          material={materials['White-PW-MT11050-5']}
          position={[0.339, 0.383, 0.902]}
          rotation={[0.928, 0.137, -0.18]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-01-077-3_-_Part'].geometry}
          material={materials['White-PW-MT11050-5.001']}
          position={[0.247, 0.069, 0.504]}
          rotation={[-0.668, -1.392, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-01-080-1_-_Part'].geometry}
          material={materials['color-3.023']}
          position={[0.347, -0.053, 0.015]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-01-081-1_-_Part'].geometry}
          material={materials['polished steel.005']}
          position={[-0.362, 0.254, 1.003]}
          rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['91290A336_Alloy_Steel_Socket_Head_Screw-1_-_Part'].geometry}
          material={materials['color.005']}
          position={[-0.362, -0.008, 0.063]}
          rotation={[Math.PI / 2, 0, -2.563]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['91290A336_Alloy_Steel_Socket_Head_Screw-2_-_Part'].geometry}
          material={materials['color.006']}
          position={[-0.359, 0, 0.033]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-02-01-001_01-1_-_Part'].geometry}
          material={materials['color-8.013']}
          position={[-0.311, 0, 0.051]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-02-01-002_01-1_-_Part'].geometry}
          material={materials['color-3.019']}
          position={[-0.311, 0, 0.051]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-02-01-003_01-1_-_Part'].geometry}
          material={materials['color-8.014']}
          position={[-0.311, 0, 0.051]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['91290A336_Alloy_Steel_Socket_Head_Screw-1_2_-_Part'].geometry}
          material={materials['color.009']}
          position={[0.299, -0.008, 0]}
          rotation={[Math.PI / 2, 0, -0.992]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['91290A336_Alloy_Steel_Socket_Head_Screw-2_2_-_Part'].geometry}
          material={materials['color.010']}
          position={[0.329, 0, 0.003]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-02-01-001_01-1_2_-_Part'].geometry}
          material={materials['color-8.015']}
          position={[0.311, 0, 0.051]}
          rotation={[0, -1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-02-01-002_01-1_2_-_Part'].geometry}
          material={materials['color-3.020']}
          position={[0.311, 0, 0.051]}
          rotation={[0, -1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-02-01-003_01-1_2_-_Part'].geometry}
          material={materials['color-8.016']}
          position={[0.311, 0, 0.051]}
          rotation={[0, -1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['tige_15_625mm-1_-_Part'].geometry}
          material={materials['polished steel.003']}
          position={[-0.237, 0.035, 0.462]}
          rotation={[1.781, -1.34, 0.891]}
        />
        <group position={[-0.286, 0.61, 1.003]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Congé2_-_Part'].geometry}
            material={materials['White-PW-MT11050-8.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Fractionner11_-_Part'].geometry}
            material={materials['White-PW-MT11050-8']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Fractionner12_-_Part'].geometry}
            material={materials['White-PW-MT11050-8.001']}
          />
        </group>
        <group position={[0.286, 0.61, 1.003]} rotation={[Math.PI / 2, 0, -Math.PI]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Congé2_2_-_Part'].geometry}
            material={materials['White-PW-MT11050-8.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Fractionner11_-_Part_2'].geometry}
            material={materials['White-PW-MT11050-8.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Fractionner12_-_Part_2'].geometry}
            material={materials['White-PW-MT11050-8.004']}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['92095A242_Button_Head_Hex_Drive_Screw-1_-_Part'].geometry}
          material={materials['color.017']}
          position={[0.273, 0.686, 0.997]}
          rotation={[Math.PI, 0, -0.813]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-01-030-1_-_Part'].geometry}
          material={materials['color.014']}
          position={[0, 0.686, 1.003]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-01-031-1_-_Part'].geometry}
          material={materials['color.015']}
          position={[-0.362, 0.481, 1.003]}
          rotation={[Math.PI, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-01-031-2_-_Part'].geometry}
          material={materials['color.016']}
          position={[0.362, 0.481, 1.003]}
          rotation={[Math.PI, 0, Math.PI / 2]}
        />
        <group position={[0.382, 0.257, 1.003]} rotation={[Math.PI, Math.PI / 2, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Cut-Extrude2_-_Part'].geometry}
            material={materials['color.020']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Revolve1_-_Part'].geometry}
            material={materials['color.019']}
          />
        </group>
        <group position={[0.349, 0.546, 1.003]} rotation={[2.094, -1.571, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Cut-Extrude2_2_-_Part'].geometry}
            material={materials['color.025']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Revolve1_2_-_Part'].geometry}
            material={materials['color.024']}
          />
        </group>
        <group position={[0.362, 0.466, 1.003]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Congé3_-_Part'].geometry}
            material={materials['color-49']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Congé4_-_Part'].geometry}
            material={materials['color-49.001']}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['91166A250_Zinc-Plated_Steel_Washer-1_-_Part'].geometry}
          material={materials['color.021']}
          position={[0.357, 0.258, 1.003]}
          rotation={[0, -1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['91166A250_Zinc-Plated_Steel_Washer-2_-_Part'].geometry}
          material={materials['color.022']}
          position={[0.367, 0.258, 1.003]}
          rotation={[-0.224, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['91166A250_Zinc-Plated_Steel_Washer-3_-_Part'].geometry}
          material={materials['color.026']}
          position={[0.367, 0.546, 1.003]}
          rotation={[-0.251, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['91166A250_Zinc-Plated_Steel_Washer-4_-_Part'].geometry}
          material={materials['color.027']}
          position={[0.357, 0.546, 1.003]}
          rotation={[-0.221, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['91290A330_Alloy_Steel_Socket_Head_Screw-1_-_Part'].geometry}
          material={materials['color.023']}
          position={[0.363, 0.546, 1.003]}
          rotation={[0.193, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['91290A336_Alloy_Steel_Socket_Head_Screw_(1)-1_-_Part'].geometry}
          material={materials['color.018']}
          position={[0.362, 0.258, 1.003]}
          rotation={[0, -1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EX0-01-09-02-001_03-1_-_Part'].geometry}
          material={materials['color-3.027']}
          position={[0.362, 0.464, 1.003]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EX0-01-09-02-002_03-1_-_Part'].geometry}
          material={materials['color-3.028']}
          position={[0.362, 0.524, 1.003]}
          rotation={[0, 0.804, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-01-064-1_-_Part'].geometry}
          material={materials['color-3.029']}
          position={[0.362, 0.455, 1.003]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-01-065_02-1_-_Part'].geometry}
          material={materials['White-PW-MT11050-10']}
          position={[0.362, 0.42, 1.003]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['2024_10_28_18_40_52_0424stp-1_-_Part'].geometry}
          material={materials['color-55']}
          position={[0.362, 0.42, 1.003]}
          rotation={[0, -1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['ball_for_PHSA6-1_-_Part'].geometry}
          material={materials['chromium plate']}
          position={[0.362, 0.546, 1.003]}
          rotation={[-1.035, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['PHSA6-1_-_Part'].geometry}
          material={materials['brushed nickel']}
          position={[0.362, 0.546, 1.003]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['ball_for_PHSA6-1_2_-_Part'].geometry}
          material={materials['chromium plate.001']}
          position={[0.362, 0.258, 1.003]}
          rotation={[-2.107, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['PHSA6-1_2_-_Part'].geometry}
          material={materials['brushed nickel.001']}
          position={[0.362, 0.258, 1.003]}
          rotation={[0, 0, Math.PI]}
        />
        <group position={[-0.342, 0.244, 1.003]} rotation={[-Math.PI, Math.PI / 2, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Cut-Extrude2_3_-_Part'].geometry}
            material={materials['color.030']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Revolve1_3_-_Part'].geometry}
            material={materials['color.029']}
          />
        </group>
        <group position={[-0.375, 0.555, 1.003]} rotation={[2.094, -Math.PI / 2, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Cut-Extrude2_4_-_Part'].geometry}
            material={materials['color.035']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Revolve1_4_-_Part'].geometry}
            material={materials['color.034']}
          />
        </group>
        <group position={[-0.362, 0.466, 1.003]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Congé3_2_-_Part'].geometry}
            material={materials['color-49.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Congé4_2_-_Part'].geometry}
            material={materials['color-49.003']}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['91166A250_Zinc-Plated_Steel_Washer-1_2_-_Part'].geometry}
          material={materials['color.031']}
          position={[-0.367, 0.258, 1.003]}
          rotation={[0, -1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['91166A250_Zinc-Plated_Steel_Washer-2_2_-_Part'].geometry}
          material={materials['color.032']}
          position={[-0.357, 0.258, 1.003]}
          rotation={[-0.224, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['91166A250_Zinc-Plated_Steel_Washer-3_2_-_Part'].geometry}
          material={materials['color.036']}
          position={[-0.357, 0.555, 1.003]}
          rotation={[-0.251, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['91166A250_Zinc-Plated_Steel_Washer-4_2_-_Part'].geometry}
          material={materials['color.037']}
          position={[-0.367, 0.555, 1.003]}
          rotation={[-0.221, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['91290A330_Alloy_Steel_Socket_Head_Screw-1_2_-_Part'].geometry}
          material={materials['color.033']}
          position={[-0.361, 0.555, 1.003]}
          rotation={[0.193, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['91290A336_Alloy_Steel_Socket_Head_Screw_(1)-1_2_-_Part'].geometry}
          material={materials['color.028']}
          position={[-0.362, 0.258, 1.003]}
          rotation={[0, -1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EX0-01-09-02-001_03-1_2_-_Part'].geometry}
          material={materials['color-3.030']}
          position={[-0.362, 0.464, 1.003]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EX0-01-09-02-002_03-1_2_-_Part'].geometry}
          material={materials['color-3.031']}
          position={[-0.362, 0.533, 1.003]}
          rotation={[0, 0.804, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-01-064-1_2_-_Part'].geometry}
          material={materials['color-3.032']}
          position={[-0.362, 0.464, 1.003]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-01-065_02-1_2_-_Part'].geometry}
          material={materials['White-PW-MT11050-10.001']}
          position={[-0.362, 0.42, 1.003]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['2024_10_28_18_40_52_0424stp-1_-_Part_2'].geometry}
          material={materials['color-55.001']}
          position={[-0.362, 0.407, 1.003]}
          rotation={[0, -1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['ball_for_PHSA6-1_3_-_Part'].geometry}
          material={materials['chromium plate.002']}
          position={[-0.362, 0.555, 1.003]}
          rotation={[-1.035, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['PHSA6-1_3_-_Part'].geometry}
          material={materials['brushed nickel.002']}
          position={[-0.362, 0.555, 1.003]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['ball_for_PHSA6-1_4_-_Part'].geometry}
          material={materials['chromium plate.003']}
          position={[-0.362, 0.258, 1.003]}
          rotation={[-2.107, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['PHSA6-1_4_-_Part'].geometry}
          material={materials['brushed nickel.003']}
          position={[-0.362, 0.258, 1.003]}
          rotation={[0, 0, -Math.PI]}
        />
        <group position={[0, 0.192, 1.026]} rotation={[0.725, 0, -1.959]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern11_-_Part_5'].geometry}
            material={materials['color.099']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern12_-_Part_5'].geometry}
            material={materials['color.100']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern13_-_Part_5'].geometry}
            material={materials['color.101']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern14_-_Part_5'].geometry}
            material={materials['color.102']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern15_-_Part_5'].geometry}
            material={materials['color.103']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern16_-_Part_5'].geometry}
            material={materials['color.104']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern17_-_Part_5'].geometry}
            material={materials['color.105']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Revolve11_-_Part_5'].geometry}
            material={materials['color.107']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Revolve12_-_Part_5'].geometry}
            material={materials['color.108']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Revolve2_5_-_Part'].geometry}
            material={materials['color.098']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Revolve31_-_Part_5'].geometry}
            material={materials['color.106']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Revolve32_-_Part_5'].geometry}
            material={materials['color.109']}
          />
        </group>
        <group position={[0, 0.159, 1.063]} rotation={[0.725, 0, -1.485]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern11_-_Part_6'].geometry}
            material={materials['color.111']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern12_-_Part_6'].geometry}
            material={materials['color.112']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern13_-_Part_6'].geometry}
            material={materials['color.113']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern14_-_Part_6'].geometry}
            material={materials['color.114']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern15_-_Part_6'].geometry}
            material={materials['color.115']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern16_-_Part_6'].geometry}
            material={materials['color.116']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern17_-_Part_6'].geometry}
            material={materials['color.117']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Revolve11_-_Part_6'].geometry}
            material={materials['color.119']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Revolve12_-_Part_6'].geometry}
            material={materials['color.120']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Revolve2_6_-_Part'].geometry}
            material={materials['color.110']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Revolve31_-_Part_6'].geometry}
            material={materials['color.118']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Revolve32_-_Part_6'].geometry}
            material={materials['color.121']}
          />
        </group>
        <group position={[0, 0.208, 1.008]} rotation={[0.725, 0, -Math.PI / 2]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern2_-_Part'].geometry}
            material={materials['satin finish aluminum-2.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern4_-_Part'].geometry}
            material={materials['satin finish aluminum-2.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Combine1_-_Part'].geometry}
            material={materials['satin finish aluminum-2.002']}
          />
        </group>
        <group position={[0, 0.209, 1.007]} rotation={[-2.417, 0, Math.PI]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern2_2_-_Part'].geometry}
            material={materials['satin finish aluminum-2.006']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern4_2_-_Part'].geometry}
            material={materials['satin finish aluminum-2.007']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Combine1_2_-_Part'].geometry}
            material={materials['satin finish aluminum-2.005']}
          />
        </group>
        <group position={[0.044, 0.351, 0.895]} rotation={[-2.155, 0, Math.PI]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Boss-Extrude31_-_Part'].geometry}
            material={materials['white-pw-mt11050']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Boss-Extrude32_-_Part'].geometry}
            material={materials['white-pw-mt11050.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Boss-Extrude33_-_Part'].geometry}
            material={materials['white-pw-mt11050.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Fillet5_-_Part'].geometry}
            material={materials['white-pw-mt11050.003']}
          />
        </group>
        <group position={[0, 0.268, 0.941]} rotation={[-2.417, 0, Math.PI / 2]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Dummy_Motor-1_-_Part'].geometry}
            material={materials['satin finish aluminum']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Dummy_Motor-1_-_Part_2'].geometry}
            material={materials['satin finish aluminum (Cosmetic Thread)']}
          />
        </group>
        <group position={[-0.016, 0.277, 0.842]} rotation={[0.987, -Math.PI / 2, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Dummy_Motor-2_-_Part'].geometry}
            material={materials['satin finish aluminum.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Dummy_Motor-2_-_Part_2'].geometry}
            material={materials['satin finish aluminum (Cosmetic Thread).001']}
          />
        </group>
        <group position={[0, 0.227, 0.987]} rotation={[2.296, 1.309, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['EXO-01-04_11-1_-_Part'].geometry}
            material={materials['matte steel']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['EXO-01-04_11-1_-_Part_2'].geometry}
            material={materials['matte steel (Cosmetic Thread)']}
          />
        </group>
        <group position={[0.029, 0.202, 1.088]} rotation={[-2.417, Math.PI / 2, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP11_-_Part_5'].geometry}
            material={materials['color-8.018']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP12_-_Part_5'].geometry}
            material={materials['color-19.020']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP13_-_Part_5'].geometry}
            material={materials['color-8.019']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP14_-_Part_5'].geometry}
            material={materials['color-19.021']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP15_-_Part_5'].geometry}
            material={materials['color-20.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP16_-_Part_5'].geometry}
            material={materials['color-19.022']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP17_-_Part_5'].geometry}
            material={materials['color-19.023']}
          />
        </group>
        <group position={[-0.056, 0.196, 0.931]} rotation={[2.034, -Math.PI / 2, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP11_-_Part_6'].geometry}
            material={materials['color-8.020']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP12_-_Part_6'].geometry}
            material={materials['color-19.024']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP13_-_Part_6'].geometry}
            material={materials['color-8.021']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP14_-_Part_6'].geometry}
            material={materials['color-19.025']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP15_-_Part_6'].geometry}
            material={materials['color-20.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP16_-_Part_6'].geometry}
            material={materials['color-19.026']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP17_-_Part_6'].geometry}
            material={materials['color-19.027']}
          />
        </group>
        <group position={[-0.053, 0.208, 0.917]} rotation={[-0.584, 1.571, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP11_-_Part_7'].geometry}
            material={materials['color-8.022']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP12_-_Part_7'].geometry}
            material={materials['color-19.028']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP13_-_Part_7'].geometry}
            material={materials['color-8.023']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP14_-_Part_7'].geometry}
            material={materials['color-19.029']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP15_-_Part_7'].geometry}
            material={materials['color-20.006']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP16_-_Part_7'].geometry}
            material={materials['color-19.030']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP17_-_Part_7'].geometry}
            material={materials['color-19.031']}
          />
        </group>
        <group position={[0, 0.198, 1.057]} rotation={[-2.417, Math.PI / 2, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Solenoid_Small_Lock_12VDCSTEP<1>1_-_Part'].geometry}
            material={materials['color-74']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Solenoid_Small_Lock_12VDCSTEP<1>2_-_Part'].geometry}
            material={materials['color-74.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Solenoid_Small_Lock_12VDCSTEP<1>3_-_Part'].geometry}
            material={materials['color-74.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Solenoid_Small_Lock_12VDCSTEP<1>4_-_Part'].geometry}
            material={materials['color-74.003']}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['9845T14_Durometer_98A_Spider_for_1_OD_and_25_mm_OD_Vibrate-'].geometry}
          material={materials['glossy rubber-2']}
          position={[0, 0.209, 1.007]}
          rotation={[0.725, 0, -2.356]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['COVER_B-1_-_Part'].geometry}
          material={materials['white-pw-mt11050-4']}
          position={[0, 0.153, 1.071]}
          rotation={[-0.846, -1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['COVER_L-1_-_Part'].geometry}
          material={materials['white-pw-mt11050-2']}
          position={[-0.044, 0.351, 0.895]}
          rotation={[0.987, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['COVER_ROUND-1_-_Part'].geometry}
          material={materials['white-pw-mt11050-5']}
          position={[0, 0.202, 1.125]}
          rotation={[-0.846, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-04_01-3_-_Part'].geometry}
          material={materials['color.096']}
          position={[0, 0.261, 0.949]}
          rotation={[-0.846, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-04_02-1_-_Part'].geometry}
          material={materials['satin finish aluminum-2']}
          position={[0, 0.234, 0.979]}
          rotation={[2.296, -1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-04_03-1_-_Part'].geometry}
          material={materials['satin finish aluminum-2.001']}
          position={[0, 0.3, 1.01]}
          rotation={[-0.846, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-04_04-2_-_Part'].geometry}
          material={materials['color.125']}
          position={[0, 0.25, 1.036]}
          rotation={[-0.846, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-04_05-1_-_Part'].geometry}
          material={materials['color.097']}
          position={[0, 0.209, 1.112]}
          rotation={[-0.846, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-04_05-2_-_Part'].geometry}
          material={materials['color.124']}
          position={[0, 0.246, 1.071]}
          rotation={[2.296, -1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-04_06-1_-_Part'].geometry}
          material={materials['color.123']}
          position={[0, 0.218, 1.082]}
          rotation={[-0.846, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-04_07-1_-_Part'].geometry}
          material={materials['light grey high gloss plastic']}
          position={[0.041, 0.247, 0.964]}
          rotation={[-0.846, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-04_08-1_-_Part'].geometry}
          material={materials['color.093']}
          position={[0.044, 0.351, 0.895]}
          rotation={[-2.155, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-04_08-2_-_Part'].geometry}
          material={materials['color.094']}
          position={[-0.044, 0.351, 0.895]}
          rotation={[-2.155, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-04_09-2_-_Part'].geometry}
          material={materials['color-3.042']}
          position={[0, 0.211, 0.91]}
          rotation={[-2.155, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-04_10-1_-_Part'].geometry}
          material={materials['color.122']}
          position={[-0.045, 0.247, 0.964]}
          rotation={[-0.846, -1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-04_14-1_-_Part'].geometry}
          material={materials['satin finish stainless steel.002']}
          position={[0, 0.191, 1.028]}
          rotation={[-0.846, 1.552, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-04_16-1_-_Part'].geometry}
          material={materials['color.126']}
          position={[0.024, 0.333, 0.908]}
          rotation={[0.987, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-04_17-1_-_Part'].geometry}
          material={materials['color-8.024']}
          position={[-0.056, 0.247, 0.964]}
          rotation={[0.725, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-04_17-2_-_Part'].geometry}
          material={materials['color-8.025']}
          position={[-0.06, 0.247, 0.964]}
          rotation={[1.51, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-04_18-1_-_Part'].geometry}
          material={materials['light grey high gloss plastic.003']}
          position={[0.044, 0.312, 0.921]}
          rotation={[-1.565, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['HTD_Pulley_H5M-1_-_Part'].geometry}
          material={materials['light grey high gloss plastic.001']}
          position={[0.056, 0.247, 0.964]}
          rotation={[-2.417, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['HTD_Pulley_H5M-2_-_Part'].geometry}
          material={materials['light grey high gloss plastic.002']}
          position={[0.056, 0.277, 0.842]}
          rotation={[-2.417, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['LILY_THIN_BEARING_6838-1_-_Part'].geometry}
          material={materials['color.095']}
          position={[0.028, 0.247, 0.964]}
          rotation={[0.725, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Part2^EXO-01-04-2_-_Part'].geometry}
          material={materials['color-3.046']}
          position={[0.058, 0.31, 0.891]}
          rotation={[-0.292, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Part2^EXO-01-04-3_-_Part'].geometry}
          material={materials['color-3.047']}
          position={[0.062, 0.31, 0.891]}
          rotation={[-0.292, 0, Math.PI / 2]}
        />
        <group position={[-0.026, 0.202, 1.088]} rotation={[-2.417, Math.PI / 2, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP11_-_Part_8'].geometry}
            material={materials['color-8.026']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP12_-_Part_8'].geometry}
            material={materials['color-19.032']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP13_-_Part_8'].geometry}
            material={materials['color-8.027']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP14_-_Part_8'].geometry}
            material={materials['color-19.033']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP15_-_Part_8'].geometry}
            material={materials['color-20.007']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP16_-_Part_8'].geometry}
            material={materials['color-19.034']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP17_-_Part_8'].geometry}
            material={materials['color-19.035']}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-04_07-3_-_Part'].geometry}
          material={materials['light grey high gloss plastic.004']}
          position={[-0.041, 0.247, 0.964]}
          rotation={[-0.846, -1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-04_16-2_-_Part'].geometry}
          material={materials['color.127']}
          position={[-0.024, 0.333, 0.908]}
          rotation={[0.987, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['LILY_THIN_BEARING_6838-2_-_Part'].geometry}
          material={materials['color-3.045']}
          position={[-0.041, 0.247, 0.964]}
          rotation={[0.725, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['MOTOR_C-1_-_Part'].geometry}
          material={materials['white-pw-mt11050-3']}
          position={[0, 0.264, 0.945]}
          rotation={[-2.417, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Part1^EXO-01-04-1_-_Part'].geometry}
          material={materials['glossy rubber']}
          position={[0.056, 0.351, 0.895]}
          rotation={[-0.584, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Part2^EXO-01-04-1_-_Part'].geometry}
          material={materials['color-3.043']}
          position={[0.054, 0.31, 0.891]}
          rotation={[-0.292, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['TPU_COVER-1_-_Part'].geometry}
          material={materials['color-3.044']}
          position={[0, 0.318, 0.987]}
          rotation={[-0.846, -1.571, 0]}
        />
        <group position={[0.149, 0.17, 0.998]} rotation={[-0.846, -1.55, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['<M2_x_25_Screw_head>-<Move_Face1>_-_Part'].geometry}
            material={materials['polished steel.009']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Body-MoveCopy4_-_Part'].geometry}
            material={materials['polished steel.010']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Cut-Extrude7_-_Part'].geometry}
            material={materials['polished steel.008']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Cut-Extrude9_-_Part'].geometry}
            material={materials['polished steel.011']}
          />
        </group>
        <group position={[0.16, 0.186, 0.997]} rotation={[-0.846, 0.021, Math.PI / 2]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Boss-Extrude1_-_Part'].geometry}
            material={materials['color-19.039']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP11_-_Part_9'].geometry}
            material={materials['color-8.031']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP12_-_Part_9'].geometry}
            material={materials['color-19.036']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP13_-_Part_9'].geometry}
            material={materials['color-8.032']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP14_-_Part_9'].geometry}
            material={materials['color-19.037']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP17_-_Part_9'].geometry}
            material={materials['color-19.038']}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-07-0011_01-1_-_Part'].geometry}
          material={materials['color-8.028']}
          position={[0.149, 0.13, 1.048]}
          rotation={[-0.06, 0.015, -0.015]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-07-006_02-1_-_Part'].geometry}
          material={materials['satin finish aluminum-2.008']}
          position={[0.166, 0.189, 0.743]}
          rotation={[3.081, -0.015, -3.127]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-07-006_03-1_-_Part'].geometry}
          material={materials['color-8.030']}
          position={[0.123, 0.19, 0.744]}
          rotation={[3.081, -0.015, -3.127]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-07-006_03_side-1_-_Part'].geometry}
          material={materials['White-PW-MT11050-12']}
          position={[0.123, 0.19, 0.744]}
          rotation={[3.081, -0.015, -3.127]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-07-016_02-1_-_Part'].geometry}
          material={materials['White-PW-MT11050-11']}
          position={[0.146, 0.189, 0.744]}
          rotation={[-0.06, 0.015, -0.015]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-07-021_01-1_-_Part'].geometry}
          material={materials['color.128']}
          position={[0.147, 0.195, 0.843]}
          rotation={[-0.06, 0.015, -0.015]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-07-022_01-1_-_Part'].geometry}
          material={materials['White-PW-MT11050-13']}
          position={[0.149, 0.147, 1.002]}
          rotation={[2.296, -0.021, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-07-029_03-1_-_Part'].geometry}
          material={materials['color-8.033']}
          position={[0.117, 0.175, 0.753]}
          rotation={[0.235, 0.01, -0.019]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-07-036_02-1_-_Part'].geometry}
          material={materials['color-8.029']}
          position={[0.151, 0.209, 1.044]}
          rotation={[-0.06, 0.015, -0.015]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-07-038_02-2_-_Part'].geometry}
          material={materials['polished steel.007']}
          position={[0.15, 0.261, 0.912]}
          rotation={[2.296, 1.55, -2.9]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-07-042_01-1_-_Part'].geometry}
          material={materials['White-PW-MT11050-14']}
          position={[0.179, 0.2, 0.963]}
          rotation={[-0.846, -1.55, -Math.PI / 4]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-07-043_01-1_-_Part'].geometry}
          material={materials['White-PW-MT11050-15']}
          position={[0.106, 0.194, 0.854]}
          rotation={[2.296, 1.55, -2.356]}
        />
        <group position={[0.139, 0.184, 0.996]} rotation={[2.296, -0.021, -Math.PI / 2]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Boss-Extrude1_2_-_Part'].geometry}
            material={materials['color-19.043']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP11_-_Part_10'].geometry}
            material={materials['color-8.034']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP12_-_Part_10'].geometry}
            material={materials['color-19.040']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP13_-_Part_10'].geometry}
            material={materials['color-8.035']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP14_-_Part_10'].geometry}
            material={materials['color-19.041']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP17_-_Part_10'].geometry}
            material={materials['color-19.042']}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-07-006_02-2_-_Part'].geometry}
          material={materials['satin finish aluminum-2.009']}
          position={[0.123, 0.19, 0.744]}
          rotation={[3.081, -0.015, -3.127]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['MirrorEXO-01-07-006_03-2_-_Part'].geometry}
          material={materials['color-8.036']}
          position={[0.169, 0.189, 0.743]}
          rotation={[-0.06, 0.015, -0.015]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['MirrorEXO-01-07-042_01-2_-_Part'].geometry}
          material={materials['White-PW-MT11050-14.001']}
          position={[0.12, 0.201, 0.964]}
          rotation={[-0.846, -1.55, -Math.PI / 4]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['MirrorEXO-01-07-043_01-2_-_Part'].geometry}
          material={materials['White-PW-MT11050-15.001']}
          position={[0.189, 0.193, 0.853]}
          rotation={[2.296, 1.55, -2.356]}
        />
        <group position={[-0.025, 0.578, 1.043]} rotation={[0.175, -Math.PI / 2, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['EXO-02-01-017-1_-_Part'].geometry}
            material={materials['color-3.010']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['EXO-02-01-017-1_-_Part_2'].geometry}
            material={materials['color-10']}
          />
        </group>
        <group position={[0.003, 0.578, 1.043]} rotation={[-0.218, Math.PI / 2, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['EXO-02-01-025-1_-_Part'].geometry}
            material={materials['color-13']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['EXO-02-01-025-1_-_Part_2'].geometry}
            material={materials['color-3.012']}
          />
        </group>
        <group position={[0, 0.686, 1.003]} rotation={[1.222, -Math.PI / 2, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Congé1_-_Part'].geometry}
            material={materials['color-8.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Fillet2_-_Part'].geometry}
            material={materials['color-8.006']}
          />
        </group>
        <group position={[0, 0.686, 1.003]} rotation={[1.222, -Math.PI / 2, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Congé1_2_-_Part'].geometry}
            material={materials['color-3.018']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Enlèv_mat-Extru5_-_Part'].geometry}
            material={materials['color-3.017']}
          />
        </group>
        <group position={[0.032, 0.578, 1.043]} rotation={[-Math.PI / 9, Math.PI / 2, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['EXO-02-01-035-1_-_Part'].geometry}
            material={materials['polished steel']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['EXO-02-01-035-1_-_Part_2'].geometry}
            material={materials['color-22']}
          />
        </group>
        <group position={[0, 0.399, 0.934]} rotation={[-1.027, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Chanfrein1_-_Part'].geometry}
            material={materials['color-3.013']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Chanfrein2_-_Part'].geometry}
            material={materials['color-3.014']}
          />
        </group>
        <group position={[-0.039, 0.589, 0.975]} rotation={[-3.002, -Math.PI / 2, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP<1>1_-_Part'].geometry}
            material={materials['color-8.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP<1>2_-_Part'].geometry}
            material={materials['color-19']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP<1>3_-_Part'].geometry}
            material={materials['color-8.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP<1>4_-_Part'].geometry}
            material={materials['color-19.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP<1>5_-_Part'].geometry}
            material={materials['color-20']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP<1>6_-_Part'].geometry}
            material={materials['color-19.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP<1>7_-_Part'].geometry}
            material={materials['color-19.003']}
          />
        </group>
        <group position={[-0.037, 0.525, 1.086]} rotation={[-2.234, Math.PI / 2, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP11_-_Part_2'].geometry}
            material={materials['color-8.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP12_-_Part_2'].geometry}
            material={materials['color-19.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP13_-_Part_2'].geometry}
            material={materials['color-8.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP14_-_Part_2'].geometry}
            material={materials['color-19.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP15_-_Part_2'].geometry}
            material={materials['color-20.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP16_-_Part_2'].geometry}
            material={materials['color-19.006']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP17_-_Part_2'].geometry}
            material={materials['color-19.007']}
          />
        </group>
        <group position={[0.045, 0.548, 1.095]} rotation={[-2.112, Math.PI / 2, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP11_-_Part_3'].geometry}
            material={materials['color-8.009']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP12_-_Part_3'].geometry}
            material={materials['color-19.012']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP13_-_Part_3'].geometry}
            material={materials['color-8.010']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP14_-_Part_3'].geometry}
            material={materials['color-19.013']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP15_-_Part_3'].geometry}
            material={materials['color-20.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP16_-_Part_3'].geometry}
            material={materials['color-19.014']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP17_-_Part_3'].geometry}
            material={materials['color-19.015']}
          />
        </group>
        <group position={[0.037, 0.608, 0.99]} rotation={[-3.126, -Math.PI / 2, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP11_-_Part_4'].geometry}
            material={materials['color-8.011']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP12_-_Part_4'].geometry}
            material={materials['color-19.016']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP13_-_Part_4'].geometry}
            material={materials['color-8.012']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP14_-_Part_4'].geometry}
            material={materials['color-19.017']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP15_-_Part_4'].geometry}
            material={materials['color-20.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP16_-_Part_4'].geometry}
            material={materials['color-19.018']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LimitSwitchSTEP17_-_Part_4'].geometry}
            material={materials['color-19.019']}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['91290A120_Alloy_Steel_Socket_Head_Screw-1_-_Part'].geometry}
          material={materials['color.003']}
          position={[0.038, 0.59, 1.05]}
          rotation={[-1.004, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['91290A137_Alloy_Steel_Socket_Head_Screwsat-1_-_Part'].geometry}
          material={materials['color-19.011']}
          position={[0, 0.642, 1.079]}
          rotation={[-2.183, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['91290A348_Alloy_Steel_Socket_Head_Screwsat-1_-_Part'].geometry}
          material={materials['color-19.009']}
          position={[0.004, 0.676, 0.977]}
          rotation={[-1.004, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['91290A351_Alloy_Steel_Socket_Head_Screwsat-1_-_Part'].geometry}
          material={materials['color-19.010']}
          position={[-0.002, 0.642, 0.978]}
          rotation={[-1.326, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['91290A456_Alloy_Steel_Socket_Head_Screwsat-1_-_Part'].geometry}
          material={materials['color-19.008']}
          position={[0.018, 0.687, 1.003]}
          rotation={[-1.92, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['91290A462_Alloy_Steel_Socket_Head_Screw-1_-_Part'].geometry}
          material={materials['color.002']}
          position={[0.012, 0.474, 0.979]}
          rotation={[-1.004, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['91290A462_Alloy_Steel_Socket_Head_Screw-2_-_Part'].geometry}
          material={materials['color.004']}
          position={[0.012, 0.495, 0.992]}
          rotation={[-1.004, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['ak80-64stp-1_-_Part'].geometry}
          material={materials['color-2']}
          position={[0.028, 0.578, 1.043]}
          rotation={[-1.004, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['bearing_6822_2rs_01-1_-_Part'].geometry}
          material={materials['color-3']}
          position={[-0.023, 0.578, 1.043]}
          rotation={[-1.597, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['bearing_6822_2rs_02-1_-_Part'].geometry}
          material={materials['color-3.001']}
          position={[-0.023, 0.578, 1.043]}
          rotation={[-1.597, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['bearing_6822_2rs_03-1_-_Part'].geometry}
          material={materials['color-3.002']}
          position={[-0.023, 0.578, 1.043]}
          rotation={[-1.597, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['bearing_6822_2rs_04-1_-_Part'].geometry}
          material={materials['color-3.003']}
          position={[-0.023, 0.578, 1.043]}
          rotation={[-1.597, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['bearing_6822_2rs_05-1_-_Part'].geometry}
          material={materials['color-3.004']}
          position={[-0.023, 0.578, 1.043]}
          rotation={[-1.597, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-02-01-002-1_-_Part'].geometry}
          material={materials['satin finish stainless steel']}
          position={[0, 0.384, 0.925]}
          rotation={[-1.027, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['bearing_6822_2rs_01-1_2_-_Part'].geometry}
          material={materials['color-3.005']}
          position={[0.007, 0.578, 1.043]}
          rotation={[1.155, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['bearing_6822_2rs_02-1_2_-_Part'].geometry}
          material={materials['color-3.006']}
          position={[0.007, 0.578, 1.043]}
          rotation={[1.155, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['bearing_6822_2rs_03-1_2_-_Part'].geometry}
          material={materials['color-3.007']}
          position={[0.007, 0.578, 1.043]}
          rotation={[1.155, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['bearing_6822_2rs_04-1_2_-_Part'].geometry}
          material={materials['color-3.008']}
          position={[0.007, 0.578, 1.043]}
          rotation={[1.155, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['bearing_6822_2rs_05-1_2_-_Part'].geometry}
          material={materials['color-3.009']}
          position={[0.007, 0.578, 1.043]}
          rotation={[1.155, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-01-050-2_-_Part'].geometry}
          material={materials['color-8.007']}
          position={[0.027, 0.578, 1.043]}
          rotation={[-Math.PI / 9, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-01-051-1_-_Part'].geometry}
          material={materials['polished steel.002']}
          position={[0.037, 0.578, 1.043]}
          rotation={[-1.027, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-01-052-1_-_Part'].geometry}
          material={materials['color-8.008']}
          position={[-0.028, 0.578, 1.043]}
          rotation={[-Math.PI / 9, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-01-01-058-1_-_Part'].geometry}
          material={materials['White-PW-MT11050-2']}
          position={[0, 0.424, 0.95]}
          rotation={[-2.598, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-02-01-001-1_-_Part'].geometry}
          material={materials.color}
          position={[0, 0.438, 0.958]}
          rotation={[-1.027, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-02-01-015-1_-_Part'].geometry}
          material={materials['color-8']}
          position={[0, 0.578, 1.043]}
          rotation={[2.115, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-02-01-018-1_-_Part'].geometry}
          material={materials['color-3.011']}
          position={[0.033, 0.578, 1.043]}
          rotation={[-2.074, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-02-01-019-1_-_Part'].geometry}
          material={materials['color.001']}
          position={[0.041, 0.578, 1.043]}
          rotation={[2.115, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-02-01-026-1_-_Part'].geometry}
          material={materials['color-15']}
          position={[0, 0.578, 1.043]}
          rotation={[-1.038, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-02-01-027-1_-_Part'].geometry}
          material={materials['color-16']}
          position={[0.028, 0.578, 1.043]}
          rotation={[-1.027, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-02-01-028-1_-_Part'].geometry}
          material={materials['color-16.001']}
          position={[-0.028, 0.578, 1.043]}
          rotation={[-1.027, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-02-01-029-1_-_Part'].geometry}
          material={materials['White-PW-MT11050']}
          position={[0.031, 0.484, 0.986]}
          rotation={[-1.027, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-02-01-040-1_-_Part'].geometry}
          material={materials['polished steel.001']}
          position={[-0.032, 0.578, 1.043]}
          rotation={[-Math.PI / 9, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-02-01-041-1_-_Part'].geometry}
          material={materials['color-3.015']}
          position={[0.003, 0.515, 1.005]}
          rotation={[-1.425, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-02-01-044-1_-_Part'].geometry}
          material={materials['color-3.016']}
          position={[0.026, 0.578, 1.043]}
          rotation={[-1.004, -Math.PI / 2, 0]}
        />
        <group position={[0.075, 0.158, 1.029]} rotation={[-2.417, 0, Math.PI]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Chamfer1_-_Part'].geometry}
            material={materials['color.066']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Fillet2_2_-_Part'].geometry}
            material={materials['color.064']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Mirror1_-_Part'].geometry}
            material={materials['color.065']}
          />
        </group>
        <group position={[0.15, 0.184, 1.035]} rotation={[-2.417, 0, Math.PI]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern11_-_Part'].geometry}
            material={materials['color.040']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern12_-_Part'].geometry}
            material={materials['color.041']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern13_-_Part'].geometry}
            material={materials['color.042']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern14_-_Part'].geometry}
            material={materials['color.043']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern15_-_Part'].geometry}
            material={materials['color.044']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern16_-_Part'].geometry}
            material={materials['color.045']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern17_-_Part'].geometry}
            material={materials['color.046']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Revolve11_-_Part'].geometry}
            material={materials['color.048']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Revolve12_-_Part'].geometry}
            material={materials['color.049']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Revolve2_-_Part'].geometry}
            material={materials['color.039']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Revolve31_-_Part'].geometry}
            material={materials['color.047']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Revolve32_-_Part'].geometry}
            material={materials['color.050']}
          />
        </group>
        <group position={[0, 0.184, 1.035]} rotation={[-2.417, 0, Math.PI]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern11_-_Part_2'].geometry}
            material={materials['color.052']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern12_-_Part_2'].geometry}
            material={materials['color.053']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern13_-_Part_2'].geometry}
            material={materials['color.054']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern14_-_Part_2'].geometry}
            material={materials['color.055']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern15_-_Part_2'].geometry}
            material={materials['color.056']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern16_-_Part_2'].geometry}
            material={materials['color.057']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern17_-_Part_2'].geometry}
            material={materials['color.058']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Revolve11_-_Part_2'].geometry}
            material={materials['color.060']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Revolve12_-_Part_2'].geometry}
            material={materials['color.061']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Revolve2_2_-_Part'].geometry}
            material={materials['color.051']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Revolve31_-_Part_2'].geometry}
            material={materials['color.059']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Revolve32_-_Part_2'].geometry}
            material={materials['color.062']}
          />
        </group>
        <group position={[0.075, 0.176, 1.045]} rotation={[2.296, 0, -Math.PI]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['EXO-05-01_01-1_-_Part'].geometry}
            material={materials['color-8.017']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Face-8_-_Part'].geometry}
            material={materials['color-56 (Cosmetic Thread)']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Face-9_-_Part'].geometry}
            material={materials['color-56 (Cosmetic Thread).001']}
          />
        </group>
        <group position={[0.075, 0.176, 1.045]} rotation={[-2.417, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Congé7_-_Part'].geometry}
            material={materials['color-3.037']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Symétrie22_-_Part'].geometry}
            material={materials['color-3.038']}
          />
        </group>
        <group position={[0.075, 0.176, 1.045]} rotation={[-2.417, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Congé8_-_Part'].geometry}
            material={materials['color-3.039']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Congé9_-_Part'].geometry}
            material={materials['color-3.040']}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes['3567N12_L_Series_Corrosion-Resistant_Timing_Belt_Pulley-1_-_Par'].geometry
          }
          material={materials['color.063']}
          position={[0.15, 0.172, 1.049]}
          rotation={[-2.417, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-05-01_02-2_-_Part'].geometry}
          material={materials['color.038']}
          position={[0.075, 0.186, 1.033]}
          rotation={[2.296, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-05-01_03-1_-_Part'].geometry}
          material={materials['color-3.033']}
          position={[0.15, 0.188, 1.031]}
          rotation={[2.296, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-05-01_04-1_-_Part'].geometry}
          material={materials['color-3.034']}
          position={[0.075, 0.168, 1.017]}
          rotation={[2.296, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-05-01_04-2_-_Part'].geometry}
          material={materials['color-3.035']}
          position={[0.075, 0.148, 1.04]}
          rotation={[-0.846, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-05-01_05-1_-_Part'].geometry}
          material={materials['color-3.036']}
          position={[0.075, 0.158, 1.029]}
          rotation={[2.296, 0, -Math.PI]}
        />
        <group position={[0.15, 0.167, 1.054]} rotation={[0.725, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern11_-_Part_3'].geometry}
            material={materials['color.069']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern12_-_Part_3'].geometry}
            material={materials['color.070']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern13_-_Part_3'].geometry}
            material={materials['color.071']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern14_-_Part_3'].geometry}
            material={materials['color.072']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern15_-_Part_3'].geometry}
            material={materials['color.073']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern16_-_Part_3'].geometry}
            material={materials['color.074']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern17_-_Part_3'].geometry}
            material={materials['color.075']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Revolve11_-_Part_3'].geometry}
            material={materials['color.077']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Revolve12_-_Part_3'].geometry}
            material={materials['color.078']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Revolve2_3_-_Part'].geometry}
            material={materials['color.068']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Revolve31_-_Part_3'].geometry}
            material={materials['color.076']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Revolve32_-_Part_3'].geometry}
            material={materials['color.079']}
          />
        </group>
        <group position={[0, 0.167, 1.054]} rotation={[0.725, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern11_-_Part_4'].geometry}
            material={materials['color.081']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern12_-_Part_4'].geometry}
            material={materials['color.082']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern13_-_Part_4'].geometry}
            material={materials['color.083']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern14_-_Part_4'].geometry}
            material={materials['color.084']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern15_-_Part_4'].geometry}
            material={materials['color.085']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern16_-_Part_4'].geometry}
            material={materials['color.086']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['CirPattern17_-_Part_4'].geometry}
            material={materials['color.087']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Revolve11_-_Part_4'].geometry}
            material={materials['color.089']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Revolve12_-_Part_4'].geometry}
            material={materials['color.090']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Revolve2_4_-_Part'].geometry}
            material={materials['color.080']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Revolve31_-_Part_4'].geometry}
            material={materials['color.088']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Revolve32_-_Part_4'].geometry}
            material={materials['color.091']}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-05-01_02-3_-_Part'].geometry}
          material={materials['color.067']}
          position={[0.075, 0.166, 1.056]}
          rotation={[2.296, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['EXO-05-01_03-2_-_Part'].geometry}
          material={materials['color-3.041']}
          position={[0.15, 0.164, 1.058]}
          rotation={[-0.846, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes['3567N12_L_Series_Corrosion-Resistant_Timing_Belt_Pulley-2_-_Par'].geometry
          }
          material={materials['color.092']}
          position={[0, 0.172, 1.049]}
          rotation={[-2.417, 0, Math.PI]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/prototype.glb')
export default Prototype;