// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  alternative_text: dynamic(() => import("./AlternativeText")),
  fade_in_text: dynamic(() => import("./FadeInText")),
  hero: dynamic(() => import("./Hero")),
  interface: dynamic(() => import("./Interface")),
};
